# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KMITL_Subject_review_application' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KMITL_Subject_review_application
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'

  target 'KMITL_Subject_review_applicationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KMITL_Subject_review_applicationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
